/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package escuela;

/**
 *
 * @author zuh19
 */
public class Escuela extends javax.swing.JFrame {

    /**
     * Creates new form Escuela
     */
    public Escuela() {
        initComponents();
        
        initPintar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jt_Nombre = new javax.swing.JTextField();
        jt_Apellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jt_Mates = new javax.swing.JTextField();
        jt_EdFisica = new javax.swing.JTextField();
        jt_Catalan = new javax.swing.JTextField();
        jt_NotaMedia = new javax.swing.JTextField();
        jb_Iniciar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jt_NotaMaxima = new javax.swing.JTextField();
        jb_Anterior = new javax.swing.JButton();
        jb_Siguiente = new javax.swing.JButton();
        jb_Final = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido");

        jt_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_NombreActionPerformed(evt);
            }
        });

        jt_Apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_ApellidoActionPerformed(evt);
            }
        });

        jLabel3.setText("Mates");

        jLabel4.setText("Educación Física");

        jLabel5.setText("Catalán");

        jLabel6.setText("Nota Media");

        jt_Mates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_MatesActionPerformed(evt);
            }
        });

        jt_EdFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_EdFisicaActionPerformed(evt);
            }
        });

        jb_Iniciar.setText("INICIAR");
        jb_Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_IniciarActionPerformed(evt);
            }
        });

        jLabel7.setText("Nota Máxima");

        jb_Anterior.setText("ANTERIOR");
        jb_Anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_AnteriorActionPerformed(evt);
            }
        });

        jb_Siguiente.setText("SIGUIENTE");

        jb_Final.setText("FINAL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jb_Iniciar)
                .addGap(18, 18, 18)
                .addComponent(jb_Anterior)
                .addGap(18, 18, 18)
                .addComponent(jb_Siguiente)
                .addGap(18, 18, 18)
                .addComponent(jb_Final)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jt_NotaMedia)
                    .addComponent(jt_Nombre)
                    .addComponent(jt_Apellido)
                    .addComponent(jt_Mates)
                    .addComponent(jt_EdFisica)
                    .addComponent(jt_Catalan)
                    .addComponent(jt_NotaMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jt_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jt_Mates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_EdFisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jt_Catalan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_NotaMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jt_NotaMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_Anterior)
                    .addComponent(jb_Iniciar)
                    .addComponent(jb_Siguiente)
                    .addComponent(jb_Final))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_IniciarActionPerformed
        
    }//GEN-LAST:event_jb_IniciarActionPerformed

    private void jt_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_NombreActionPerformed
        String myName=String.valueOf(this.jt_Nombre);
    }//GEN-LAST:event_jt_NombreActionPerformed

    private void jt_ApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_ApellidoActionPerformed
        String mySurname=String.valueOf(this.jt_Apellido);
    }//GEN-LAST:event_jt_ApellidoActionPerformed

    private void jt_MatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_MatesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_MatesActionPerformed

    private void jt_EdFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_EdFisicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_EdFisicaActionPerformed

    private void jb_AnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_AnteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_AnteriorActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void initPintar(){
        Alumno alu = new Alumno("Pepe","Garcia",7,5,9);
        this.jt_Nombre.setText(alu.getNombre());
        this.jt_Apellido.setText(alu.getApellido());
        //Pasar 
        this.jt_Mates.setText(String.valueOf(alu.getNotaMates()));
        this.jt_EdFisica.setText(String.valueOf(alu.getNotaEdFisica()));
        this.jt_Catalan.setText(String.valueOf(alu.getNotaCatalan()));
        
        float resultado = alu.notamedia(alu.getNotaMates(), alu.getNotaCatalan(), alu.getNotaEdFisica());
        this.jt_NotaMedia.setText(String.valueOf(resultado));
        float notaMaxima= alu.notaMaxima(alu.getNotaCatalan(), alu.getNotaEdFisica(), alu.getNotaMates());
        this.jt_NotaMaxima.setText(String.valueOf(notaMaxima));
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escuela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Escuela().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jb_Anterior;
    private javax.swing.JButton jb_Final;
    private javax.swing.JButton jb_Iniciar;
    private javax.swing.JButton jb_Siguiente;
    private javax.swing.JTextField jt_Apellido;
    private javax.swing.JTextField jt_Catalan;
    private javax.swing.JTextField jt_EdFisica;
    private javax.swing.JTextField jt_Mates;
    private javax.swing.JTextField jt_Nombre;
    private javax.swing.JTextField jt_NotaMaxima;
    private javax.swing.JTextField jt_NotaMedia;
    // End of variables declaration//GEN-END:variables
}
